### ISSUE TITLE
Add gaussian blur as option for transparent background color?

### ISSUE THREAD

**Issue by rafaelmaeuer** [ejprok/colorful_safe_area#1]
First of all thanks for this great component!!! This is more a kind of feature request than an issue:
Would it be possible to think about adding a gaussian blur as option to transparent background color? This would enable Cupertino-Style Apps which have the same style on status bar and bottom navigation bar (CupertinoTabBar).

**Comment by ejprok** [comment]
@rafaelmaeuer Thanks for giving the component a try!   I am actually currently working on adding a blur effect.  I just created a new branch just for this feature.   The pictures below show my current progress, though I am not ready to officially add it to the package because of the issue in the 2nd image.  This problem occurs when any of the sides of the ColorfulSafeArea touch, making the blurring look inconsistent.  
<img width="400" alt="Screen Shot 2020-05-01 at 3 27 59 PM" src="https://user-images.githubusercontent.com/17091545/80846607-a87dff00-8bc1-11ea-8fc9-cde243d29160.png">

<img width="300" alt="Screen Shot 2020-05-01 at 3 28 24 PM" src="https://user-images.githubusercontent.com/17091545/80846518-5dfc8280-8bc1-11ea-8c49-16007fde25d3.png">

**Comment by ejprok** [comment]
If anyone wants to try out the new branch for the blur effect, use this in your pubspec.yaml

`  colorful_safe_area: 
    git:
      url: git://github.com/ejprok/colorful_safe_area
      ref: blur`

**Comment by rafaelmaeuer** [comment]
Thanks for the quick reply, I tried it using the branch 'blur' and it works very nice for me.

**Comment by ejprok** [comment]
Latest version of the package now has the blur effect.

**Comment by rafaelmaeuer** [comment]
👍🏻
